/** Seed posts when localStorage is empty — same shape as admin-created posts. */
export const defaultBlogPosts = [
  {
    id: "seed-proma",
    slug: "hi-im-mayesha-maliha-proma",
    category: "personal",
    thoughtCategory: "personal",
    featuredOnHome: true,
    title: "Hi, I'm Mayesha Maliha Proma",
    date: "2026-05-19",
    paragraphs: [
      {
        text: "From early on, I was friends with everyone, yet I had my own circles. I danced, painted, sang, and explored all kinds of classes. These experiences shaped my curiosity, diversity, and leadership. I notice how people respond, how attention flows, and how to guide energy. I also know how to follow, which is just as important.",
        marginNote: "curiosity starts early",
        highlighted: false,
      },
      {
        text: "I like figuring things out my way and seeing how different paths connect. That curiosity now shapes everything I do.",
        marginNote: "my own way",
        highlighted: true,
      },
    ],
    pullQuote: "Curious, diverse, leading my own way from the start.",
    signature: "— Mayesha Maliha Proma",
    signatureMeta: "from Bangladesh to Japan",
  },
  {
    id: "seed-founder",
    slug: "founder-story",
    category: "founder",
    thoughtCategory: "founder",
    featuredOnHome: true,
    title: "Founder",
    date: "2026-05-19",
    paragraphs: [
      {
        text: "I have always been fascinated by how the world works, why people take risks, and how ventures shape lives. This curiosity drew me to study abroad and eventually help others navigating the same journey. In 2022, I started AbroadMates to make the complex simple for students.",
        marginNote: "why ventures",
        highlighted: false,
      },
      {
        text: "Now I'm building ApplicationMate, or Mate, to feel like a friend, present and helping whenever needed. I've realized that taking risks is part of the fun and discovery. Ventures like this can solve almost anything if approached thoughtfully.",
        marginNote: "building Mate",
        highlighted: true,
      },
    ],
    pullQuote: "Everything draws me in, risk is fun, ventures solve.",
    signature: "— Mayesha Maliha Proma",
    signatureMeta: "founder · ApplicationMate",
  },
  {
    id: "seed-researcher",
    slug: "researcher",
    category: "research",
    thoughtCategory: "research",
    title: "Researcher",
    date: "2026-05-19",
    paragraphs: [
      {
        text: "I love digging deep, peeling layers, and following questions to their limits. Curiosity drives me and I don't stop until I understand the core.",
        marginNote: "go deep",
        highlighted: false,
      },
      {
        text: "I bring all my interests together in one focus. Every student I work with and every teammate I see struggling with decisions makes me think. I treat my startup as a lab, my products as experiments, and explore how people can make better, clearer decisions. My research is about understanding complexity and turning it into insight that matters.",
        marginNote: "startup as lab",
        highlighted: true,
      },
    ],
    pullQuote: "I go deep, ask the last question, learn from it.",
    signature: "— Mayesha Maliha Proma",
    signatureMeta: "research · decisions",
  },
  {
    id: "seed-traveler",
    slug: "traveler",
    category: "travel",
    thoughtCategory: "travel",
    featuredOnHome: true,
    title: "Traveler",
    date: "2026-05-19",
    paragraphs: [
      {
        text: "I travel with my boyfriend and feel most relaxed. I follow, watch, and think. I don't document everything. I observe people, places, and how cultures blend in.",
        marginNote: "follow & watch",
        highlighted: false,
      },
      {
        text: "When I return home, I reimagine those moments. That reflection fuels my work and creativity. Each year, I try to spend time working from different geographies. Seeing life in new ways gives me fresh perspectives and ideas.",
        marginNote: "reflection fuels work",
        highlighted: true,
      },
    ],
    pullQuote: "I follow, watch, think, and reflect on the world.",
    signature: "— Mayesha Maliha Proma",
    signatureMeta: "notes from the road",
  },
  {
    id: "seed-chaos",
    slug: "the-chaos-i-couldnt-ignore",
    category: "founder",
    thoughtCategory: "founder",
    featuredOnHome: true,
    title: "The chaos I couldn't ignore",
    date: "2026-05-19",
    paragraphs: [
      {
        text: "I have always been the kind of person who wanted to figure things out on my own. Even as a kid, I liked exploring, searching for answers, and finding my own way. I would look at something, taste it, enjoy it, and then think, I want others to experience this too. That drive to share good experiences and make things clearer has always been with me.",
        marginNote: "on my own",
        highlighted: false,
      },
      {
        text: "When I decided to study abroad, I wanted to do it on my own. I started searching, experimenting, and learning everything I could. Then Covid happened, and everything shifted. It brought me here, and by now you probably understand where that curiosity and persistence led me.",
        marginNote: "then Covid",
        highlighted: false,
      },
      {
        text: "I ran into a system that was confusing, designed more to extract money than to provide guidance. Agencies sold dreams without accountability. Students were left misled, alone, and unsure of their next steps.",
        marginNote: "the system",
        highlighted: false,
      },
      {
        text: "I self-applied to universities across Japan, figuring it out through trial and error, and eventually earned a full-tuition scholarship to Tokyo International University for Digital Business and Innovation.",
        marginNote: "scholarship",
        highlighted: false,
      },
      {
        text: "That experience changed me deeply. I realized I wanted to build something better for everyone. I wanted to make confusing systems understandable, accessible, and supportive. With that in mind, I co-founded The Abroad Company with Rahat. We launched AbroadMates, a peer-to-peer mentorship platform, and started building ApplicationMate, an AI copilot for study abroad applications.",
        marginNote: "build better",
        highlighted: true,
      },
      {
        text: "Along the way, I fell in love with programming, coding, and analysis. I started using my numerical skills to understand how people think and how they make decisions, especially in the high-stakes areas I work in. As my co-founder often says, these are decisions that matter deeply, and helping people make them more thoughtfully is critical. Combining curiosity, technology, and a desire to help people, I realized I could turn complexity into clarity.",
        marginNote: "complexity → clarity",
        highlighted: false,
      },
    ],
    pullQuote:
      "This drives me every day. I care about making confusing systems understandable, guiding people to make better decisions, learning constantly, and sharing what I discover so others can benefit from it.",
    signature: "— Mayesha Maliha Proma",
    signatureMeta: "from Bangladesh to Japan",
  },
  {
    id: "seed-halfway-there",
    slug: "halfway-there",
    category: "personal",
    thoughtCategory: "personal",
    featuredOnHome: true,
    title: "Halfway there",
    date: "2026-08-22",
    paragraphs: [
      {
        text: "For a long time, the term “women’s rights” unsettled me. I kept wondering: why not human rights? Why should women need a separate category to be treated as human? Growing up in Bangladesh, that question became harder to ignore. I saw expectations placed on women that were treated as normal, even when they restricted their choices.",
        marginNote: "why not human rights",
        highlighted: false,
      },
      {
        text: "Whenever I heard something unfair, I argued with family and friends. For a while, I believed people might change. By 18, I understood that the problem was deeper than individual opinions. It extended to women’s financial independence, support, and freedom of choice. I wanted to do more than argue, so I started an e-learning initiative to help women develop income-generating skills and explored building a women-led community where they could support one another against discrimination.",
        marginNote: "more than argue",
        highlighted: false,
      },
      {
        text: "Trying to build those ideas taught me something harder: caring deeply about a problem did not mean I knew how to solve it. I lacked the experience needed for lasting change. That realization shaped my decision to study abroad on scholarship. I wanted experiences that would challenge me, strengthen me, and prepare me for problems I was not ready to face. I still feel halfway there. I left because I knew I needed to become stronger first. I want to return better equipped to face the problem that pushed me to leave.",
        marginNote: "leave to return",
        highlighted: true,
      },
    ],
    pullQuote: "I left because I knew I needed to become stronger first.",
    signature: "— Mayesha Maliha Proma",
    signatureMeta: "from the essays",
  },
  {
    id: "seed-twenty-years",
    slug: "what-still-matters-in-twenty-years",
    category: "research",
    thoughtCategory: "research",
    title: "What still matters in twenty years",
    date: "2026-08-22",
    paragraphs: [
      {
        text: "When I was choosing before undergrad, I kept asking myself what would still matter in this world twenty years from now. That question pulled me toward data science and eventually led me to study Digital Business and Innovation. Since then, that curiosity has grown through building AI and data-driven ventures and researching NLP, AI, and especially how humans interact with AI. The more I build, the more questions I have, and the more I want to understand what is happening inside.",
        marginNote: "the long question",
        highlighted: false,
      },
      {
        text: "Making something work is one thing, but making it intuitive for people is completely different. I run into that problem all the time while building products: how information is structured and made useful. Whichever path I take next, I want to keep moving between building and research — build something, then learn from how people use it.",
        marginNote: "build, then watch",
        highlighted: true,
      },
    ],
    pullQuote: "The more I build, the more questions I have.",
    signature: "— Mayesha Maliha Proma",
    signatureMeta: "from the essays",
  },
  {
    id: "seed-ask-before-assuming",
    slug: "ask-before-assuming",
    category: "personal",
    thoughtCategory: "personal",
    title: "Ask before assuming",
    date: "2026-08-22",
    paragraphs: [
      {
        text: "I grew up believing that if something was considered “ideal” in my family, school, or community, it was the right way to do things. I followed those ideals without asking whether they were right for us, rather than right for everyone. Living in Japan made me question that.",
        marginNote: "the ideal",
        highlighted: false,
      },
      {
        text: "One day, while teaching English to a Japanese student, I told him about a trip to Vietnam and complained about food I had found difficult to eat. Later, I asked what he thought about eating rice with your hands, which is normal in my culture but uncommon in Japan. I expected him to react negatively. Instead, he said he found it interesting. He had even tried it himself, but the rice kept falling from his hand.",
        marginNote: "the rice kept falling",
        highlighted: false,
      },
      {
        text: "That answer hit me. I had become so used to expecting judgment that I did not expect curiosity. At the same time, I realized that I had just spoken about Vietnamese food in the same way I disliked hearing people speak about my own culture. That moment became a course correction. I learned that something unfamiliar does not have to be treated as wrong. It can be different. Since then, I have tried to question my reaction. Ask before assuming and listen before deciding. I now bring the same habit into my work: instead of starting with what I think people need, I try to understand the problem first.",
        marginNote: "different is not wrong",
        highlighted: true,
      },
    ],
    pullQuote: "Something unfamiliar does not have to be treated as wrong. It can be different.",
    signature: "— Mayesha Maliha Proma",
    signatureMeta: "from the essays",
  },
  {
    id: "seed-what-feels-small",
    slug: "what-feels-small",
    category: "personal",
    thoughtCategory: "personal",
    title: "What feels small",
    date: "2026-08-22",
    paragraphs: [
      {
        text: "I first joined as a volunteer on a day spent with orphaned children — food, clothes, books, gifts, games, and simply time. That first experience made me want to do more than participate once a year.",
        marginNote: "show up",
        highlighted: false,
      },
      {
        text: "Later I helped plan “Coding for Orphans,” meant to teach programming as a practical skill children could eventually use to become more independent. The project could not be fully carried out because of circumstances beyond our control. It taught me how difficult it is to turn a good intention into something sustainable.",
        marginNote: "intention is not enough",
        highlighted: false,
      },
      {
        text: "I continued returning whenever I could. The experience changed how I understood charity: sometimes, what feels small from my side — a few hours, a book, a meal, or simply showing up — can mean much more to someone receiving it. That realization made me want to keep doing what I could.",
        marginNote: "what feels small",
        highlighted: true,
      },
    ],
    pullQuote: "What feels small from my side can mean much more to someone receiving it.",
    signature: "— Mayesha Maliha Proma",
    signatureMeta: "from the essays",
  },
  {
    id: "seed-different-working-norms",
    slug: "different-working-norms",
    category: "personal",
    thoughtCategory: "personal",
    title: "Different working norms",
    date: "2026-08-22",
    paragraphs: [
      {
        text: "I started a data science community for students who wanted to learn the field more deeply than our interdisciplinary major allowed. I worked with professors on a focused plan, then handled university approval, recruited members, and built the team that ran it. Even forming a club took layers of paperwork. No category existed for us. After months of documents, negotiations, and interviews in Japanese and English, the university created a new category for educational activities and made us its first member.",
        marginNote: "no category existed",
        highlighted: false,
      },
      {
        text: "Students learned at different speeds, so I built a level-based path — SQL, Python, statistics, introductory machine learning — so someone could study, take a test, and move on when ready. More than seventy students completed it. Some later joined research teams. Others used the skills for internships.",
        marginNote: "their own pace",
        highlighted: false,
      },
      {
        text: "Leading that club with members from many countries taught me that people approach the same goal in very different ways. They balance speed and perfection differently. They make decisions differently. Now, when I am leading, I take time to understand each person’s working norms, then set expectations.",
        marginNote: "understand first",
        highlighted: true,
      },
    ],
    pullQuote: "People from different cultures approach the same goal in very different ways.",
    signature: "— Mayesha Maliha Proma",
    signatureMeta: "from the essays",
  },
  {
    id: "seed-not-good-enough",
    slug: "not-good-enough",
    category: "personal",
    thoughtCategory: "personal",
    title: "Not good enough",
    date: "2026-08-22",
    paragraphs: [
      {
        text: "I rarely stop at “good enough.” I add thoughtful details that make people feel considered. My extended family and friends often turn to me when a difficult decision needs to be made. I can switch between very different roles quickly and stay focused when several things demand attention.",
        marginNote: "three things",
        highlighted: true,
      },
    ],
    pullQuote: "I rarely stop at good enough.",
    signature: "— Mayesha Maliha Proma",
    signatureMeta: "from the essays",
  },
];
